name: "CF Push"
description: Push an application to a Cloud Foundry
inputs:
  manifest:
    description: The path to your CF application manifest
    required: true
  api:
    description: The Cloud Foundry API endpoint
    required: true
  username:
    description: Your Cloud Foundry authentication username (or email address)
    required: true
  password:
    description: Your Cloud Foundry authentication password
    required: true
  org:
    description: The name of the Cloud Foundry organization in which to deploy
    required: true
  space:
    description: The name of the Cloud Foundry space in which to deploy
    required: true
  validate:
    description: Whether or not to validate the CF API's TLS certificate
    required: false
    default: true

runs:
  using: docker
  image: Dockerfile
