FROM node:16.20.2-alpine
WORKDIR /opt/node_app/app

COPY package.json package-lock.json ./
COPY tsconfig.json ./

RUN npm ci --no-optional

COPY . .

ENV PORT=9009
EXPOSE 9009

CMD ["npm", "run", "dev"]
