# This is a basic workflow to help you get started with Actions

name: Update Staging Env

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  # workflow_call:
  #   secrets:
  #     STAGE_CF_USERNAME:
  #       description: cf-login username
  #       required: true
  #     STAGE_CF_PASSWORD:
  #       description: cf-login password
  #       required: true

jobs:
  push_secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Update Login.gov creds on cloud.gov
        uses: cloud-gov/cg-cli-tools@main
        with:
          cf_api: https://api.fr.cloud.gov
          cf_username: ${{secrets.STAGE_CF_USERNAME}}
          cf_password: ${{secrets.STAGE_CF_PASSWORD}}
          cf_org: gsa-open-opportunities
          cf_space: USDS
          cf_command: cf set-env smeqa-staging LOGIN_KEY "${{secrets.STAGE_LOGIN_KEY_11_22_21}}"
